### PR TITLE
feat: set release_status to Production/Stable

### PR DESCRIPTION
**Pull request by busunkim96**
Release-As: 1.0.0

Proposed release: **GA**

## Instructions

Check the lists below, adding tests / documentation as required. Once all the "required" boxes are ticked, please create a release and close this issue.

## Required

- [x] 28 days elapsed since last beta release with new API surface (last release on [2/5/2020](https://github.com/googleapis/python-monitoring/releases/tag/v0.34.0))
- [x] Server API is GA ([v3](https://github.com/googleapis/python-monitoring/tree/master/google/cloud/monitoring_v3))
- [x] Package API is stable, and we can commit to backward compatibility
- [x] All dependencies are GA

## Optional

- [ ] Most common / important scenarios have descriptive samples
- [ ] Public manual methods have at least one usage sample each (excluding overloads)
- [ ] Per-API README includes a full description of the API
- [ ] Per-API README contains at least one “getting started” sample using the most common API scenario
- [ ] Manual code has been reviewed by API producer
- [ ] Manual code has been reviewed by a DPE responsible for samples
- [ ] 'Client Libraries' page is added to the product documentation in 'APIs & Reference' section of the product's documentation on Cloud Site

### CODE REVIEW

**Comment by jskeet** [comment]
Please don't release just yet - we're trying to work out some breaking changes. Hopefully they won't affect things anyway as they come from changes later than the last commit in this repo, but it's possible there will be more.

**Comment by danoscarmike** [comment]
@busunkim96 @jskeet we're no longer blocked on this correct?

**Comment by jskeet** [comment]
Unsure off-hand - let's chat internally.

**Comment by busunkim96** [comment]
Merged the pending PR.

**Pull request merged**
